### ISSUE TITLE
Recording screenshots does not work on emulator API 30

### ISSUE THREAD

**Issue by darek-nowak** [pedrovgs/Shot#240] opened 2021-07-05 12:36 UTC
### Expected behaviour
Recording screenshot should work on emulator with API 30

### Actual behaviour
Using version 5.8.0 of a lib. When running recording screenshot task `./gradlew executeScreenshotTests -Precord` you get error that screenshots can not be pulled from the directory. Directory simply does not exist.
```
>Task :app:debugDownloadScreenshots
Pulling screenshots from your connected devices:
Shot ADB warning: We could not pull screenshots from folder: /storage/emulated/0/Download/screenshots/myapp.com.test/screenshots-default
Shot ADB warning: rm: /storage/emulated/0/Download/screenshots/myapp.com.test/screenshots-default/: No such file or directory
```

### Steps to reproduce
Run with emulator with API 30 task:
./gradlew executeScreenshotTests -Precord

### Version of the library
5.8.0

**Comment by sergioartalejoN26** [comment] 2021-07-08 13:26
Having the same issue here

**Comment by pedrovgs** [comment] 2021-07-29 14:55
Hey @darek-nowak could you please upload a reproducible sample? I've checked it out and it works. Maybe there's something wrong with your project configuration. Could you review the config and also check if it works with an older emulator API?

**Comment by pedrovgs** [comment] 2021-12-22 12:14
I've merged and released a PR by @mariuszmarzec that tentatively fixes this issue. Could you please guys check if 5.12.2 version and reopen this issue if it doesn't work?

**Closed by pedrovgs** 2021-12-22 12:14 UTC
Labels: bug

**Comment by mariuszmarzec** [comment] 2022-07-30 11:44
@akshay-at-yml 
```
org.apache.commons.io.FileExistsException: Destination 'C:\Users\LATITUDE\AndroidStudioProjects\LiveProjects\HealthCare\app\s
creenshots\debug\screenshots-compose-default\metadata_compose.json_RZ8M32BQJRM' already exists
```
Looks like this temporary dir `C:\Users\LATITUDE\AndroidStudioProjects\LiveProjects\HealthCare\app\s
creenshots\debug\screenshots-compose-default` wasn't removed from some reason. Remove it manually and other dirs under debug dir, should help.
